LNAME = TEST
LNAME = SEO
FNAME = MINKYU

LNAME += MANSOO

NAME = '"SEO"'

A = $(B) AA
B = BB

a := $(b) aa
b := bb

all:
	@echo $(NAME)
#	@echo A= $(A)
#	@echo a= $(a)
#	@echo LNAME= $(LNAME)
#	@echo ${LANME}, $(FNAME)
#	@echo MR. $(LNAME)
